name: simple_cash_app_day
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.5.3+2
  cached_network_image: ^3.2.1
  # cached_network_image: ^3.2.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
   - assets/

  fonts:
    - family: Prompt
      fonts:
        - asset: assets/font/Prompt-Regular.ttf

flutter_gen:
  colors:
    inputs:
      - assets/colors/colors.xml

